Some adjustements

diff --git a/.github/workflows/dependency-audit.yml b/.github/workflows/dependency-audit.yml
--- a/.github/workflows/dependency-audit.yml
+++ b/.github/workflows/dependency-audit.yml
@@ -3,11 +3,16 @@ name: dependency-audit.yml
 on:
   pull_request:
     types: [ opened, synchronize, reopened ]
+  push:
+    branches:
+      - '**'
+    paths:
+      - 'pyproject.toml'
 
 jobs:
   dependency_audit:
     runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request' && github.event.action == 'opened'
+    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.event.pull_request != null)
     permissions:
       contents: read
       pull-requests: write
@@ -50,7 +55,7 @@ jobs:
         id: audit
         continue-on-error: true
         run: |
-          echo "## 🛡️ Secutiry audit" > audit.md
+          echo "## 🛡️ Security audit" > audit.md
           pip-audit --format json > audit.json || true
           if [ -s audit.json ] && grep -q '"vulnerabilities":' audit.json; then
             echo "⚠️ **Found vulnerabilities:**" >> audit.md
@@ -68,7 +73,7 @@ jobs:
           fi
 
       - name: 💬 Comment on PR
-        uses: actions/github-script@v7
+        uses: actions/github-script@v8
         with:
           script: |
             const fs = require('fs');
@@ -87,5 +92,5 @@ jobs:
       - name: ❌ Fail if vulnerabilities found
         if: env.HAS_VULNERABILITIES == 'true'
         run: |
-          echo "::error::Vulerabilities found on dependencies."
+          echo "::error::Vulnerabilities found on dependencies."
           exit 1
